# Generated by Django 3.2.7 on 2021-09-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('city', models.CharField(choices=[('asheville', 'Asheville'), ('durham', 'Durham'), ('atlanta', 'Atlanta')], default='Asheville', max_length=40)),
                ('street', models.CharField(max_length=40)),
                ('zip', models.IntegerField()),
                ('phone', models.IntegerField(unique=True)),
            ],
        ),
    ]
