# Generated by Django 3.2.7 on 2021-09-23 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdl', '0002_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('day', models.CharField(choices=[('all', 'ALL'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('frisatsun', 'Fri/Sat/Sun')], default='ALL', max_length=40)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fdl.restaurant')),
            ],
        ),
    ]
