# Generated by Django 3.2.7 on 2021-10-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdl', '0003_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='time',
            field=models.CharField(choices=[('all_times', 'ALL Times'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('late night', 'Late Night'), ('brunch', 'Brunch')], default='ALL TIMES', max_length=40),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='day',
            field=models.CharField(choices=[('all_days', 'ALL DAYS'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='ALL DAYS', max_length=40),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.FloatField(),
        ),
    ]
