# Generated by Django 3.2.7 on 2021-10-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdl', '0004_auto_20211004_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='dietary',
            field=models.CharField(choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan')], default='ALL DIETS', max_length=40),
        ),
    ]
