# Generated by Django 3.2.7 on 2021-10-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdl', '0005_menuitem_dietary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='dietary',
            field=models.CharField(choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('gluten_free', 'Gluten-Free')], default='ALL DIETS', max_length=40),
        ),
    ]
