# Generated by Django 3.2.7 on 2021-10-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdl', '0007_alter_menuitem_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='dietary',
            field=models.CharField(choices=[('none', 'none'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('gluten_free', 'Gluten-Free')], default='none', max_length=40),
        ),
    ]
