# Generated by Django 3.2.7 on 2021-10-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdl', '0009_auto_20211004_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='long_lat',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
