# Generated by Django 3.2.7 on 2021-10-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdl', '0010_restaurant_long_lat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='long_lat',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.IntegerField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.IntegerField(blank=True, max_length=40, null=True),
        ),
    ]
