# Generated by Django 3.2.7 on 2021-10-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdl', '0012_auto_20211004_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='time',
            field=models.CharField(choices=[('all_times', 'ALL Times'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('late_night', 'Late Night'), ('brunch', 'Brunch'), ('lunch_dinner', 'Lunch and Dinner'), ('breakfast_and_lunch', 'Breakfast and Lunch'), ('breakfast_lunch_dinner', 'Breakfast lunch and dinner'), ('dinner_and_late_night', 'Dinner and Late Night')], default='ALL TIMES', max_length=40),
        ),
    ]
