# Generated by Django 3.2.7 on 2021-10-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdl', '0014_alter_menuitem_dietary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='dietary',
            field=models.CharField(choices=[('none', 'none'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('gluten_free', 'Gluten-Free'), ('vegetarian_and_gf', 'Vegetarian and GF'), ('vegan', 'Vegan and GF')], default='none', max_length=40),
        ),
    ]
