# Generated by Django 3.2.7 on 2021-10-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdl', '0017_alter_menuitem_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='close_time',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='open_time',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
