# Generated by Django 3.2.7 on 2021-10-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdl', '0018_auto_20211005_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='coordinates',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
