# Generated by Django 3.2.7 on 2021-10-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdl', '0019_restaurant_coordinates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
