# Generated by Django 3.2.7 on 2021-10-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdl', '0020_delete_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
