# Generated by Django 3.2.7 on 2021-10-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdl', '0022_alter_restaurant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
