# Generated by Django 3.2.7 on 2021-10-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdl', '0024_alter_restaurant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
