# Generated by Django 3.2.7 on 2021-10-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdl', '0027_auto_20211019_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='dietary',
            field=models.CharField(blank='none', choices=[('none', 'none'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('gluten_free', 'Gluten-Free'), ('vegetarian_and_gf', 'Vegetarian and GF'), ('vegan_and_gf', 'Vegan and GF')], default='none', max_length=40, null='none'),
        ),
    ]
