# Generated by Django 3.2.7 on 2021-10-19 15:09

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('fdl', '0028_alter_menuitem_dietary'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='dietary',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('gluten_free', 'Gluten-Free'), ('vegetarian_and_gf', 'Vegetarian and GF'), ('vegan_and_gf', 'Vegan and GF')], default='none', max_length=40, null=True),
        ),
    ]
