# Generated by Django 3.2.7 on 2021-10-19 16:03

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('fdl', '0029_auto_20211019_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
