# Generated by Django 3.2.7 on 2021-10-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdl', '0030_alter_menuitem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='dietary',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Gluten-free', 'Gluten-free'), ('Vegetarian and Gluten-free', 'Vegetarian and GF'), ('Vegan and Gluten-free', 'Vegan and GF'), ('Dairy-free', 'Dairy-free')], default='none', max_length=40, null=True),
        ),
    ]
