# Generated by Django 3.2.7 on 2021-10-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdl', '0032_alter_menuitem_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='day',
            field=models.CharField(blank=True, choices=[('all_days', 'ALL DAYS'), ('weekends', 'Weekends'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='ALL DAYS', max_length=40, null=True),
        ),
    ]
