# Generated by Django 3.2.7 on 2021-10-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdl', '0034_alter_menuitem_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(choices=[('asheville', 'Asheville'), ('durham', 'Durham'), ('atlanta', 'Atlanta'), ('nyc', 'NYC')], default='Asheville', max_length=40),
        ),
    ]
