# Generated by Django 3.2.7 on 2021-10-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdl', '0035_alter_restaurant_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
